project_id = "fwoescubnnagdvwasbjl"

[functions.booking-api]
verify_jwt = false


[functions.chatbot-runtime]
verify_jwt = false

[functions.embed-plan-status]
verify_jwt = false

[functions.sync-embed-plan]
verify_jwt = false

[functions.provision-account]
verify_jwt = false

[functions.crawl]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false


