services:
  server:
    image: talkbuilder-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatbot-server
    restart: always
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - EVO_BASE_URL=${EVO_BASE_URL}
      - EVO_GLOBAL_KEY=${EVO_GLOBAL_KEY}
      - PORT=3000
    networks:
      - builderchat_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-server.rule=Host(`${SERVER_DOMAIN}`)"
      - "traefik.http.routers.chatbot-server.entrypoints=websecure"
      - "traefik.http.routers.chatbot-server.tls=true"
      # - "traefik.http.routers.chatbot-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.chatbot-server.loadbalancer.server.port=3000"
      - "traefik.docker.network=builderchat_net"

  frontend:
    image: talkbuilder-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID}
        - VITE_RUNTIME_URL=${VITE_RUNTIME_URL}
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    container_name: chatbot-frontend
    restart: always
    networks:
      - builderchat_net
    labels:
      - "traefik.enable=true"
      # Router HTTPS
      - "traefik.http.routers.chatbot-frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.chatbot-frontend.entrypoints=websecure"
      - "traefik.http.routers.chatbot-frontend.tls=true"
      # - "traefik.http.routers.chatbot-frontend.tls.certresolver=letsencrypt"
      # Router HTTP (Redirecionamento para HTTPS)
      - "traefik.http.routers.chatbot-frontend-http.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.chatbot-frontend-http.entrypoints=web"
      - "traefik.http.routers.chatbot-frontend-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # Service
      - "traefik.http.services.chatbot-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=builderchat_net"

networks:
  builderchat_net:
    external: true
